name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test-release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 13.x
      uses: actions/setup-node@v1
      with:
        node-version: 13.x
    - name: Install
      run: yarn install --no-progress --non-interactive --skip-integrity-check
    - name: Build
      run : yarn build
    - name: Check
      run: |
        yarn test
        yarn prettier-check
      env:
        CI: true
    - name: Semantic Release
      if: github.ref == 'refs/heads/master'
      uses: codfish/semantic-release-action@v1
      with:
        branch: master
