# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test-release:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 13.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: yarn install --no-progress --non-interactive --skip-integrity-check
    - name: Build
      run : yarn build
    - name: Check
      run: |
        yarn test
        yarn prettier-check
      env:
        CI: true
    - name: Semantic Release
      if: github.ref == 'refs/heads/master'
      uses: codfish/semantic-release-action@v1
      with:
        branch: master
